force-app/main/default/objects/Blood_Coordination__c/Blood_Coordination__c.object-meta.xml
<CustomObject>
    <label>Blood Coordination</label>
    <nameField>
        <label>Blood Coordination Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blood Coordinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Blood_Coordination__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <label>Donor</label>
    <referenceTo>Blood_donor__c</referenceTo>
    <relationshipLabel>Blood Coordinations</relationshipLabel>
    <relationshipName>Blood_Coordinations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Blood_Coordination__c/fields/Donor_name__c.field-meta.xml
<CustomField>
    <fullName>Donor_name__c</fullName>
    <formula>Donor__r.donor_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Donor name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blood_Coordination__c/fields/patient__c.field-meta.xml
<CustomField>
    <fullName>patient__c</fullName>
    <label>patient</label>
    <referenceTo>blood_request__c</referenceTo>
    <relationshipLabel>Blood Coordinations</relationshipLabel>
    <relationshipName>Blood_Coordinations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Blood_Coordination__c/fields/patient_name__c.field-meta.xml
<CustomField>
    <fullName>patient_name__c</fullName>
    <formula>patient__r.patient_name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>patient name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blood_donor__c/Blood_donor__c.object-meta.xml
<CustomObject>
    <label>Blood donor</label>
    <nameField>
        <displayFormat>BD-{000}</displayFormat>
        <label>Donor ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>blood donors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Blood_donor__c/fields/blood_group__c.field-meta.xml
<CustomField>
    <fullName>blood_group__c</fullName>
    <label>blood group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>O POSITIVE</fullName>
            </value>
            <value>
                <fullName>O NEGETIVE</fullName>
            </value>
            <value>
                <fullName>A POSITIVE</fullName>
            </value>
            <value>
                <fullName>A NEGETIVE</fullName>
            </value>
            <value>
                <fullName>B POSITIVE</fullName>
            </value>
            <value>
                <fullName>B NEGETIVE</fullName>
            </value>
            <value>
                <fullName>AB POSITIVE</fullName>
            </value>
            <value>
                <fullName>AB NEGETIVE</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blood_donor__c/fields/donor_name__c.field-meta.xml
<CustomField>
    <fullName>donor_name__c</fullName>
    <description>name of the blood donor</description>
    <label>donor name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Blood_donor__c/fields/weight__c.field-meta.xml
<CustomField>
    <fullName>weight__c</fullName>
    <description>enter the weight of the donor in kgs</description>
    <label>weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/blood_request__c/blood_request__c.object-meta.xml
<CustomObject>
    <description>details of patients who require blood</description>
    <label>blood request</label>
    <nameField>
        <label>blood request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>blood requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/blood_request__c/fields/attender_name__c.field-meta.xml
<CustomField>
    <fullName>attender_name__c</fullName>
    <description>enter the person name who is requesting blood for the patient</description>
    <label>attender name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/blood_request__c/fields/patient_name__c.field-meta.xml
<CustomField>
    <fullName>patient_name__c</fullName>
    <description>name of the patient who needs blood</description>
    <label>patient name</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <label>DOB</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/assin6.cls
public class assin6 {

    
    public contact acc_con(string Name1,Integer num1,string lastname1,integer num2)
    {
        Account acc=new Account(Name=Name1);
        insert acc;
        Contact con=new Contact(LastName=lastname1,AccountId=acc.Id);
        insert con;
        return con;
        
    }
    
    public Id create_Blood_Donor(string name1,Decimal weight,string bloodgrp,Date dateofbirth){
        
       Blood_donor__c bd=new Blood_donor__c(donor_name__c=name1,weight__c=weight,blood_group__c =bloodgrp,DOB__c=dateofbirth) ;
            Insert bd;
        return bd.Id;
            
    }
     public Id create_Blood_Request(string attname1,string pname,String Name2){
      
         blood_request__c br=new blood_request__c(Name=Name2,patient_name__c =pname,attender_name__c=attname1);
         insert br;
         return br.Id;
     
            
    }
    public void Create_blood_Coord(Id brId,Id bdId)
    {
        Blood_Coordination__c bc=new Blood_Coordination__c(patient__c=brId,Donor__c=bdId);
        insert bc;
    }
}
/*anonymus code
 * assin6 a6=new assin6();
Id blooddonorId=a6.create_Blood_Donor('ravi',80,'O POSITIVE',Date.newInstance(1986, 02, 19));
Id bloodrequestId=a6.create_Blood_Request('radha','poonam','sharma');
a6.Create_blood_Coord(bloodrequestId,blooddonorId);*/