force-app/main/default/objects/Account/fields/priority_field__c.field-meta.xml
<CustomField>
    <fullName>priority_field__c</fullName>
    <description>pick list to select the priority level</description>
    <label>priority field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>high</fullName>
            </value>
            <value>
                <fullName>medium</fullName>
            </value>
            <value>
                <fullName>low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <label>last name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/employee__c/employee__c.object-meta.xml
<CustomObject>
    <label>employee</label>
    <nameField>
        <label>employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/refactor12.cls
public class refactor12 {
    
   
    public static void empupdate(){
        
     list<employee__c>  emplist=new list<employee__c>();
    list<employee__c>  emprec=[Select id,Name from employee__c];
    for(employee__c emp: emprec)
    {
        
        employee__c e=new employee__c();
        e.Name=emp.Name+'refactor';
        e.id=emp.id;
        emplist.add(e);
    }
  update emplist;
    }
    
    Public static void accinsert(){
      list<Account> accnewlist=new list<Account>();
        for(integer i=0;i<5;i++)
        {
            Account singlerec =new Account();
            singlerec.Name ='Test'+i;
            singlerec.priority_field__c='high';
            accnewlist.add(singlerec);
        }
        insert accnewlist;
        
    }
    public static void coninsert(){
        list<Contact> conlist =new list<Contact>();
        for(Account acc:[Select Id,Name from Account])
        {
           Contact conrec=new Contact();
            conrec.AccountId=acc.Id;
            conrec.last_name__c='SN'+acc.Name;
            conlist.add(conrec);
           
        }
    insert conlist;
    }
    
}