force-app/main/default/objects/Customer_Project__c/Customer_Project__c.object-meta.xml
<CustomObject>
    <label>Customer Project</label>
    <nameField>
        <label>Customer Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Project__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Customer Projects</relationshipLabel>
    <relationshipName>Customer_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Active_Customer_Project__c.field-meta.xml
<CustomField>
    <fullName>Active_Customer_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Customer Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>open</fullName>
            </value>
            <value>
                <fullName>closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/customerprotriggerhandler.cls
public class customerprotriggerhandler {
    
    public static void Activefldchk(list<Customer_Project__c>  newlist)
    {
         Set<id> oppids=new Set<id>() ;
    for(Customer_Project__c c:newlist)
    {  
        if(c.Status__c=='Active' && c.OpportunityId__c !=null)
        oppids.add(c.OpportunityId__c);
    }
    list<opportunity> opplst =[Select id,Active_Customer_Project__c from Opportunity where Id IN :oppids];
    for(Opportunity o:opplst)
    {
        o.Active_Customer_Project__c =True;
    }
    update opplst;
    }

}