force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/employee__c/employee__c.object-meta.xml
<CustomObject>
    <label>employee</label>
    <nameField>
        <label>employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>employees</relationshipLabel>
    <relationshipName>employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Department.cls
public class Department {

    string Name;
    integer Employees;
    
    public static void  finddept(){
        
       List <Department__c> dep=[SELECT Name ,(select id from employees__r)   from Department__c ];
       integer maxemp=0;
        string dept;
        for(Department__c d:dep)
        {    
            integer noofemp=d.employees__r.size();
            if(noofemp>maxemp)
            {
             maxemp=noofemp;
                dept=d.Name;
            }
            system.debug(d.Name);
            system.debug(noofemp);
           //system.debug(d.employees__r.Id);
        }
        system.debug('=======================================================================');
         system.debug('department with max employees = '+dept);
            system.debug('no of employees is ='+ maxemp);
            
    }
    
    
    
}