force-app/main/default/objects/Contact/fields/mobile_number__c.field-meta.xml
<CustomField>
    <fullName>mobile_number__c</fullName>
    <label>mobile number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DmlError__c/DmlError__c.object-meta.xml
<CustomObject>
    <label>DmlError</label>
    <nameField>
        <label>DmlError Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DmlErrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DmlError__c/fields/DML_status__c.field-meta.xml
<CustomField>
    <fullName>DML_status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DML status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DmlError__c/fields/errormessage__c.field-meta.xml
<CustomField>
    <fullName>errormessage__c</fullName>
    <label>errormessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DmlError__c/fields/Id_o_fDML__c.field-meta.xml
<CustomField>
    <fullName>Id_o_fDML__c</fullName>
    <label>Id o fDML</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/processtest.cls
public class processtest {
   // @invocablemethod
    public static void create_contactrec()
    {
        list<contact> conlist=new list<contact>();
        Contact conrec=new Contact(LastName='saadhvi');
        conlist.add(conrec);
        Contact conrec2=new Contact(mobile_number__c='9246663018');
        conlist.add(conrec2);
        List<Database.SaveResult>  Result1=Database.insert(conlist,false);
        system.debug(Result1);
        list<DmlError__c> errlst =new list<DmlError__c>();
        for(Database.SaveResult ds:Result1)
        {
        
        DmlError__c  err=new DmlError__c(Id_o_fDML__c=ds.getId());
            err.Name='contactinsert';
            err.DML_status__c = ds.isSuccess();
         
            for(Database.Error e : ds.getErrors())
            {
                err.errormessage__c= e.getMessage();
            }
            errlst.add(err);
         
        
        
    }
        insert errlst;

}
}