force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <label>Receipt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Mode_of_Pay__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Pay__c</fullName>
    <label>Mode of Pay</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Id__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Id__c</fullName>
    <label>Receipt Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/receiptController.cls
public class receiptController {

    @AuraEnabled(cacheable=true)
    Public static list<Receipt__c> getReceiptRec(Id contactid)
    {
        return [Select Amount__c,Receipt_Id__c,Mode_of_Pay__c from Receipt__c where ContactId__c = :contactid];
    }
    @AuraEnabled
    public static Id create_receipt_rec(String receiptId,decimal  Amount,String modeofpay,string contactid)
    {
        Receipt__c rec=new Receipt__c();
        rec.Receipt_Id__c=receiptId;
        rec.Mode_of_Pay__c=modeofpay;
        rec.Amount__c = Amount;
        rec.ContactId__c=contactid;
        insert rec;
         system.debug(rec)  ;
        return rec.Id;
    }
}